








WITH 

PARAMETRO AS (
    SELECT 
        CONVERT(DATETIME, '04/12/2025', 103) AS DATA_PARAM,
        'Trabalhado' AS TIPO_AVISO_PREVIO  -- Parâmetro adicionado: 'Indenizado' ou 'Trabalhado'
),

DATA_REFERENCIA AS (
    SELECT 
        FUN.CODEMP,
        FUN.CODFUNC,
        CASE 
            WHEN AVI.CODFUNC IS NOT NULL AND (SELECT DATA_PARAM FROM PARAMETRO) > AVI.DTFIMAVISO THEN AVI.DTFIMAVISO
            ELSE (SELECT DATA_PARAM FROM PARAMETRO)
        END AS DATA_REF
    FROM TFPFUN FUN
    LEFT JOIN TFPAVI AVI ON AVI.CODFUNC = FUN.CODFUNC AND AVI.CODEMP = FUN.CODEMP
    WHERE FUN.SITUACAO <> 0
),

FERIAS AS (
    SELECT 
        DTINIAQUI,
        DTFINAQUI,
        DTPREVISTA,
        DTSAIDA,
        ATUALFERGOZ,
        CODFUNC,
        CODEMP,
        NUMDIASFER,
        DENSE_RANK() OVER (PARTITION BY CODFUNC, CODEMP ORDER BY DTFINAQUI DESC) AS SEQUENCIA
    FROM TFPFER
    WHERE DTSAIDA >= '2022-01-01'
),

TB_MEDIA AS (
    SELECT 
        ACU.CODEMP,
        ACU.CODFUNC,
        ACU.ANO,
        ACU.CODEVENTO,
        EVE.DESCREVENTO,
        VLRJANEIRO AS MES_01,
        VLRFEVEREIRO AS MES_02,
        VLRMARCO AS MES_03,
        VLRABRIL AS MES_04,
        VLRMAIO AS MES_05,
        VLRJUNHO AS MES_06,
        VLRJULHO AS MES_07,
        VLRAGOSTO AS MES_08,
        VLRSETEMBRO AS MES_09,
        VLROUTUBRO AS MES_10,
        VLRNOVEMBRO AS MES_11,
        VLRDEZEMBRO AS MES_12
    FROM TFPACU ACU
    LEFT JOIN TFPEVE EVE ON (EVE.CODEVENTO = ACU.CODEVENTO)
    LEFT JOIN TFPFUN FUN ON FUN.CODEMP = ACU.CODEMP AND FUN.CODFUNC = ACU.CODFUNC
    WHERE EVE.INCSOBREMEDIAS = 'S'
),

UNPVTMEDIA AS (
    SELECT 
        CODEMP,
        CODFUNC,
        ANO,
        CODEVENTO,
        DESCREVENTO,
        MES,
        VALOR
    FROM TB_MEDIA P
    UNPIVOT(VALOR FOR MES IN (MES_01, MES_02, MES_03, MES_04, MES_05, MES_06,
                            MES_07, MES_08, MES_09, MES_10, MES_11, MES_12)) AS UNPVT
),

MEDIA AS (
    SELECT 
        CODEMP,
        CODFUNC,
        ANO,
        CODEVENTO,
        DESCREVENTO,
        VALOR,
        CAST(RIGHT(MES,2) AS INT) AS MES,
        DATEFROMPARTS(ANO, CAST(RIGHT(MES,2) AS INT), 1) AS REFERENCIA 
    FROM UNPVTMEDIA
),

ULTPERAQUI AS (
    SELECT DISTINCT
        CODFUNC,
        CODEMP,
        MAX(DTINIAQUI) AS INI_ULT_PER_AQUI
    FROM FERIAS
    WHERE ATUALFERGOZ = 'S' AND DTSAIDA IS NOT NULL
    GROUP BY CODFUNC, CODEMP
),

INIPERAQUI AS (
    SELECT 
        CODFUNC,
        CODEMP,
        MAX(DTINIAQUI) AS INI_PERIODO_AQUISITIVO,
        SUM(NUMDIASFER) AS NUMDIASFER
    FROM FERIAS
    WHERE SEQUENCIA = 1
    GROUP BY CODFUNC, CODEMP
),

MD1 AS (
    SELECT 
        MED.CODEMP,
        MED.CODFUNC,
        SUM(VALOR) AS VALOR
    FROM MEDIA MED
    LEFT JOIN INIPERAQUI INI ON INI.CODEMP = MED.CODEMP AND INI.CODFUNC = MED.CODFUNC
    WHERE MED.REFERENCIA >= DATEFROMPARTS(YEAR(INI_PERIODO_AQUISITIVO), MONTH(INI_PERIODO_AQUISITIVO), 1)
    GROUP BY MED.CODEMP, MED.CODFUNC
),

SALDO_FGTS AS (
    SELECT 
        FOL.CODEMP,
        FOL.CODFUNC,
        SUM(FOL.VLREVENTO) AS SALDO_SANKHYA_FGTS
    FROM TFPFOL FOL
    INNER JOIN TFPFUN FUN ON FUN.CODEMP = FOL.CODEMP AND FUN.CODFUNC = FOL.CODFUNC
    INNER JOIN DATA_REFERENCIA DR ON DR.CODEMP = FUN.CODEMP AND DR.CODFUNC = FUN.CODFUNC
    WHERE FOL.CODEVENTO = 995
      AND FOL.REFERENCIA <= CASE 
                               WHEN FUN.DTDEM IS NOT NULL THEN FUN.DTDEM
                               ELSE DR.DATA_REF
                            END
    GROUP BY FOL.CODEMP, FOL.CODFUNC
),

FGTS_MES AS (
    SELECT 
        CODEMP,
        CODFUNC,
        REFERENCIA,
        SUM(VLREVENTO) AS FGTSMES
    FROM TFPFOL
    WHERE CODEVENTO = 995
    GROUP BY CODEMP, CODFUNC, REFERENCIA
),

COMP_SALDO AS (
    SELECT 
        CODEMP,
        CODFUNC,
        REFERENCIA,
        SUM(VLREVENTO) AS COMPSALDO
    FROM TFPFOL
    WHERE CODEVENTO IN (17, 22, 23, 24, 25, 46, 50, 53, 61, 80, 87, 90, 93, 101, 125, 128, 150, 151, 152,
                       540, 541, 552, 10000, 10001, 10002, 10003, 10011, 10017, 10020, 10023, 10024, 10029,
                       10035, 10056, 10057, 10065, 10090, 10101, 10103, 10109, 10145)
    GROUP BY CODEMP, CODFUNC, REFERENCIA
),

ULTIMA_REFERENCIA AS (
    SELECT 
        CODEMP,
        CODFUNC,
        MAX(REFERENCIA) AS REFERENCIA
    FROM TFPHFU
    GROUP BY CODEMP, CODFUNC
),

ULTIMO_SAL_BASE AS (
    SELECT
        UTR.CODEMP,
        UTR.CODFUNC,
        SALBASE
    FROM TFPHFU HFU
    INNER JOIN ULTIMA_REFERENCIA UTR ON UTR.REFERENCIA = HFU.REFERENCIA AND UTR.CODEMP = HFU.CODEMP AND UTR.CODFUNC = HFU.CODFUNC
),

COLABORADORES AS (
    SELECT
        FUN.CODEMP,
        FUN.CODFUNC,
        FUN.NOMEFUNC,
        FUN.DTADM,
        FUN.DTDEM,
		p.DATA_PARAM,
        CASE
            WHEN FUN.DTADM < DATEADD(MONTH, -12, ISNULL(FUN.DTDEM, DR.DATA_REF)) THEN DATEADD(MONTH, -12, ISNULL(FUN.DTDEM, DR.DATA_REF))
            ELSE FUN.DTADM 
        END AS REFERENCIA_DECTER,
        DATEFROMPARTS(YEAR(ISNULL(FUN.DTDEM, DR.DATA_REF)), MONTH(ISNULL(FUN.DTDEM, DR.DATA_REF)), 1) AS REFERENCIA,
        COALESCE(HISTFUN.CODDEP, FUN.CODDEP) AS CODDEP,
        COALESCE(HISTFUN.CODCARGO, FUN.CODCARGO) AS CODCARGO,
        CAR.DESCRCARGO,
        
            DAY(DATA_PARAM)
        AS DIAS_SALDO_SALARIO,
        COALESCE(FUN.AD_SALDOFGTS, 0) AS SALDO_ANTERIOR_FGTS,
        COALESCE(HISTFUN.SALBASE, FUN.SALBASE) AS SALBASE,
        (COALESCE(HISTFUN.SALBASE, FUN.SALBASE) / 30 * (30 + (FLOOR(DATEDIFF(DAY, FUN.DTADM, ISNULL(FUN.DTDEM, DR.DATA_REF)) / 365) * 3))) AS AVISO_PREVIO_INDENIZADO,
        ROUND((COALESCE(HISTFUN.SALBASE, FUN.SALBASE) / 12) * 
            ((CASE WHEN (CASE WHEN DAY(ISNULL(FUN.DTDEM, DR.DATA_REF)) = DAY(EOMONTH(ISNULL(FUN.DTDEM, DR.DATA_REF))) THEN 30 ELSE DAY(ISNULL(FUN.DTDEM, DR.DATA_REF)) END) >= 15 THEN 1 ELSE 0 END) - 
            (CASE WHEN YEAR(FUN.DTADM) < YEAR(ISNULL(FUN.DTDEM, DR.DATA_REF)) THEN 0 
                ELSE (CASE WHEN (CASE WHEN DAY(FUN.DTADM) = DAY(EOMONTH(FUN.DTADM)) THEN 30 ELSE DAY(FUN.DTADM) END) >= 15 THEN 1 ELSE 0 END) 
            END) + 
            (DATEDIFF(MONTH, CASE WHEN FUN.DTADM > DATEFROMPARTS(YEAR(ISNULL(FUN.DTDEM, DR.DATA_REF)), 1, 1) THEN FUN.DTADM ELSE DATEFROMPARTS(YEAR(ISNULL(FUN.DTDEM, DR.DATA_REF)), 1, 1) END, 
            ISNULL(FUN.DTDEM, DR.DATA_REF)))), 2) AS DECTERSALARIO,
        COALESCE(CASE 
            WHEN ISNULL(FUN.DTDEM, DR.DATA_REF) < INI_PERIODO_AQUISITIVO THEN 0 
            ELSE 30 - INI.NUMDIASFER
        END, 0) AS DIAS_FERIAS_VENCIDAS,
        CASE 
            WHEN DATEDIFF(MONTH, INI_PERIODO_AQUISITIVO, ISNULL(FUN.DTDEM, DR.DATA_REF)) = 0 THEN 0
            ELSE MD1.VALOR / DATEDIFF(MONTH, INI_PERIODO_AQUISITIVO, ISNULL(FUN.DTDEM, DR.DATA_REF)) / 30 * (30 + (FLOOR(DATEDIFF(DAY, FUN.DTADM, ISNULL(FUN.DTDEM, DR.DATA_REF)) / 365) * 3))
        END AS MEDIA_AVISO_PREVIO_INDENIZADO,
        COALESCE(HISTFUN.SALBASE, FUN.SALBASE) / 30 * (30 + (FLOOR(DATEDIFF(DAY, FUN.DTADM, ISNULL(FUN.DTDEM, DR.DATA_REF)) / 365) * 3)) / 12 * ROUND((30 + (FLOOR(DATEDIFF(DAY, FUN.DTADM, ISNULL(FUN.DTDEM, DR.DATA_REF)) / 365) * 3)) / 30, 0) AS DECTER_API 
    FROM TFPFUN FUN 
    INNER JOIN DATA_REFERENCIA DR ON DR.CODEMP = FUN.CODEMP AND DR.CODFUNC = FUN.CODFUNC
    LEFT JOIN TFPHFU HISTFUN ON FUN.CODFUNC = HISTFUN.CODFUNC AND FUN.CODEMP = HISTFUN.CODEMP
        AND HISTFUN.REFERENCIA = (SELECT MAX(REFERENCIA) FROM TFPHFU 
                                 WHERE CODEMP = FUN.CODEMP AND CODFUNC = FUN.CODFUNC 
                                 AND REFERENCIA <= ISNULL(FUN.DTDEM, DR.DATA_REF))
    LEFT JOIN TFPCAR CAR ON CAR.CODCARGO = COALESCE(HISTFUN.CODCARGO, FUN.CODCARGO)
    LEFT JOIN TFPDEP DEP ON DEP.CODDEP = COALESCE(HISTFUN.CODDEP, FUN.CODDEP)
    LEFT JOIN INIPERAQUI INI ON FUN.CODFUNC = INI.CODFUNC AND FUN.CODEMP = INI.CODEMP
    LEFT JOIN MD1 ON MD1.CODEMP = FUN.CODEMP AND MD1.CODFUNC = FUN.CODFUNC
	CROSS JOIN PARAMETRO p
    WHERE FUN.situacao <> 0
),

INSALUBRIDADE AS (
    SELECT 
        FOL.CODFUNC,
        FOL.CODEMP,
        SUM(VLREVENTO) AS VALOR
    FROM TFPFOL FOL
    JOIN COLABORADORES COL ON COL.CODEMP = FOL.CODEMP AND COL.CODFUNC = FOL.CODFUNC
    INNER JOIN DATA_REFERENCIA DR ON DR.CODEMP = COL.CODEMP AND DR.CODFUNC = COL.CODFUNC
    WHERE CODEVENTO IN (13, 14610036, 10037, 10126, 10066, 10039, 10006, 10027, 10106, 10038)
        AND FOL.REFERENCIA = DATEFROMPARTS(YEAR(ISNULL(COL.DTDEM, DR.DATA_REF)), MONTH(ISNULL(COL.DTDEM, DR.DATA_REF)), 1)
    GROUP BY FOL.CODEMP, FOL.CODFUNC
),

PERICULOSIDADE AS (
    SELECT 
        FOL.CODFUNC,
        FOL.CODEMP,
        SUM(VLREVENTO) AS VALOR
    FROM TFPFOL FOL
    JOIN COLABORADORES COL ON COL.CODEMP = FOL.CODEMP AND COL.CODFUNC = FOL.CODFUNC
    INNER JOIN DATA_REFERENCIA DR ON DR.CODEMP = COL.CODEMP AND DR.CODFUNC = COL.CODFUNC
    WHERE CODEVENTO = 11
        AND FOL.REFERENCIA = DATEFROMPARTS(YEAR(ISNULL(COL.DTDEM, DR.DATA_REF)), MONTH(ISNULL(COL.DTDEM, DR.DATA_REF)), 1)
    GROUP BY FOL.CODEMP, FOL.CODFUNC
),

MD2 AS (
    SELECT 
        MED.CODEMP,
        MED.CODFUNC,
        CASE
            WHEN DATEDIFF(MONTH, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 AND DATEDIFF(YEAR, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
            WHEN DATEDIFF(MONTH, CASE 
                                    WHEN COL.DTADM < DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF)) THEN DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF))
                                    ELSE COL.DTADM END, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
            ELSE SUM(VALOR) / DATEDIFF(MONTH, CASE 
                                                WHEN COL.DTADM < DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF)) THEN DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF))
                                                ELSE COL.DTADM END, ISNULL(COL.DTDEM, DR.DATA_REF)) / 30 * 
                                                (30 + (FLOOR(DATEDIFF(DAY, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) / 365) * 3)) / 12 *
                                                ROUND((30 + (FLOOR(DATEDIFF(DAY, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) / 365) * 3)) / 30, 0)
        END AS VALOR,
        CASE 
            WHEN DATEDIFF(MONTH, CASE
                                    WHEN COL.DTADM < DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF)) THEN DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF))
                                    ELSE COL.DTADM
                                END, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
            ELSE SUM(VALOR) / DATEDIFF(MONTH, CASE
                                                WHEN COL.DTADM < DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF)) THEN DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF))
                                                ELSE COL.DTADM
                                            END, ISNULL(COL.DTDEM, DR.DATA_REF)) / 12 * 
                 (CASE WHEN (DATEDIFF(MONTH, CASE
                                                WHEN COL.DTADM > DATEFROMPARTS(YEAR(ISNULL(COL.DTDEM, DR.DATA_REF)), 1, 1) THEN COL.DTADM
                                                ELSE DATEFROMPARTS(YEAR(ISNULL(COL.DTDEM, DR.DATA_REF)), 1, 1) 
                                                END, ISNULL(COL.DTDEM, DR.DATA_REF))) > 15 THEN 1
                      ELSE (DATEDIFF(MONTH, CASE
                                                WHEN COL.DTADM > DATEFROMPARTS(YEAR(ISNULL(COL.DTDEM, DR.DATA_REF)), 1, 1) THEN COL.DTADM
                                                ELSE DATEFROMPARTS(YEAR(ISNULL(COL.DTDEM, DR.DATA_REF)), 1, 1) 
                                                END, ISNULL(COL.DTDEM, DR.DATA_REF))) END)
        END AS VALOR_2,
        CASE 
            WHEN DATEDIFF(MONTH, CASE
                                    WHEN COL.DTADM < DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF)) THEN DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF))
                                    ELSE COL.DTADM END, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
            ELSE SUM(VALOR) / DATEDIFF(MONTH, CASE
                                                WHEN COL.DTADM < DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF)) THEN DATEADD(MONTH, -12, ISNULL(COL.DTDEM, DR.DATA_REF))
                                                ELSE COL.DTADM END, ISNULL(COL.DTDEM, DR.DATA_REF))
        END AS VALOR_3
    FROM MEDIA MED
    JOIN COLABORADORES COL ON COL.CODEMP = MED.CODEMP AND COL.CODFUNC = MED.CODFUNC
    INNER JOIN DATA_REFERENCIA DR ON DR.CODEMP = COL.CODEMP AND DR.CODFUNC = COL.CODFUNC
    WHERE MED.REFERENCIA >= COL.REFERENCIA_DECTER
    GROUP BY MED.CODEMP, MED.CODFUNC, COL.DTADM, COL.DTDEM, DR.DATA_REF
),

FERIAS_PROPORCIONAIS AS (
    SELECT 
        COL.CODEMP,
        COL.CODFUNC,
        col.SALBASE,
		case when DATEDIFF(day,cast(col.DTADM as date),GETDATE()) <15 then 0
         when (day(col.DATA_PARAM)+1 ) >=day(col.DTADM) then
		((CASE WHEN (CASE WHEN DAY(ISNULL(COL.DTDEM, DR.DATA_REF)) = DAY(EOMONTH(ISNULL(COL.DTDEM, DR.DATA_REF))) THEN 30 ELSE DAY(ISNULL(COL.DTDEM, DR.DATA_REF)) END) >= 15 THEN 1 ELSE 0 END) - 
        (CASE WHEN (CASE WHEN DAY(MAX(DTINIAQUI)) = DAY(EOMONTH(MAX(DTINIAQUI))) THEN 30 ELSE DAY(MAX(DTINIAQUI)) END) >= 15 THEN 1 ELSE 0 END) + 
        ROUND(((DATEDIFF(MONTH, MAX(DTINIAQUI), ISNULL(COL.DTDEM, DR.DATA_REF)))), 0) % 12)
		
		when (day(col.DATA_PARAM)+1 ) <day(col.DTADM) then
		((CASE WHEN (CASE WHEN DAY(ISNULL(COL.DTDEM, DR.DATA_REF)) = DAY(EOMONTH(ISNULL(COL.DTDEM, DR.DATA_REF))) THEN 30 ELSE DAY(ISNULL(COL.DTDEM, DR.DATA_REF)) END) >= 15 THEN 1 ELSE 0 END) - 
        (CASE WHEN (CASE WHEN DAY(MAX(DTINIAQUI)) = DAY(EOMONTH(MAX(DTINIAQUI))) THEN 30 ELSE DAY(MAX(DTINIAQUI)) END) >= 15 THEN 1 ELSE 0 END) + 
        ROUND(((DATEDIFF(MONTH, MAX(DTINIAQUI), ISNULL(COL.DTDEM, DR.DATA_REF)))), 0) % 12) -1
		
		end FERPROP
    FROM COLABORADORES COL
    INNER JOIN DATA_REFERENCIA DR ON DR.CODEMP = COL.CODEMP AND DR.CODFUNC = COL.CODFUNC
    LEFT JOIN FERIAS FER ON FER.CODEMP = COL.CODEMP AND FER.CODFUNC = COL.CODFUNC
	
    GROUP BY COL.CODEMP, COL.CODFUNC, SALBASE, COL.DTDEM, DR.DATA_REF,COL.DTADM,COL.DATA_PARAM
),

MD3 AS (
    SELECT 
        MED.CODEMP,
        MED.CODFUNC,
        SUM(VALOR) / 12 AS VALOR 
    FROM MEDIA MED
    LEFT JOIN INIPERAQUI INI ON INI.CODEMP = MED.CODEMP AND INI.CODFUNC = MED.CODFUNC
    LEFT JOIN COLABORADORES COL ON COL.CODEMP = MED.CODEMP AND COL.CODFUNC = MED.CODFUNC
    INNER JOIN DATA_REFERENCIA DR ON DR.CODEMP = COL.CODEMP AND DR.CODFUNC = COL.CODFUNC
    WHERE DATEDIFF(MONTH, INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF)) >= 12
        AND MED.REFERENCIA BETWEEN DATEFROMPARTS(YEAR(INI_PERIODO_AQUISITIVO), MONTH(INI_PERIODO_AQUISITIVO), 1) 
                            AND DATEADD(MONTH, 12, DATEFROMPARTS(YEAR(INI_PERIODO_AQUISITIVO), MONTH(INI_PERIODO_AQUISITIVO), 1)) 
    GROUP BY MED.CODEMP, MED.CODFUNC
),

base as(
SELECT DISTINCT
    COL.CODEMP,
    CASE 
        WHEN COL.CODEMP = 1 THEN 'IDDS'
        WHEN COL.CODEMP = 2 THEN 'AVANTE SOCIAL'
        ELSE ''
    END AS NOMEEMP,
    COL.CODFUNC,
    COL.NOMEFUNC,
    COL.DTDEM,
    COL.CODDEP,
    COL.CODCARGO,
    COL.DESCRCARGO,
    COL.DTADM,
    ULT.INI_ULT_PER_AQUI,
    INI.INI_PERIODO_AQUISITIVO,
    COL.SALBASE,
    COL.DIAS_SALDO_SALARIO,
    (COL.SALBASE + ISNULL(CPS.COMPSALDO, 0)) / 30 * DIAS_SALDO_SALARIO AS SALDO_SALARIO,
    COL.AVISO_PREVIO_INDENIZADO,
    COL.MEDIA_AVISO_PREVIO_INDENIZADO,
    ROUND((ISNULL(COL.AVISO_PREVIO_INDENIZADO, 0) + ISNULL(COL.MEDIA_AVISO_PREVIO_INDENIZADO, 0)) * 0.08, 2) AS FGTS_AVISO_IND,
    COL.DECTER_API,
    MD2.VALOR AS MEDIA_DECTER_API,
    ROUND((ISNULL(COL.DECTER_API, 0) + ISNULL(MD2.VALOR, 0)) * 0.08, 2) AS FGTS_DECTERC_API,
    COL.SALBASE / 30 * (30 + (FLOOR(DATEDIFF(DAY, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) / 365) * 3)) / 12 * ROUND((30 + (FLOOR(DATEDIFF(DAY, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) / 365) * 3)) / 30, 0) AS FERIAS_PROP_API,
   
    MD2.VALOR AS MEDIA_FERIAS_API,
    COL.SALBASE / 12 * FERPROP AS FERIAS_PROPORCIONAIS,
    CASE 
        WHEN DATEDIFF(MONTH, INI.INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
        ELSE ((COL.SALBASE / 12 * FERPROP) + 
            CASE
                WHEN DATEDIFF(MONTH, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 AND DATEDIFF(YEAR, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
                WHEN DATEDIFF(MONTH, INI.INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 AND DATEDIFF(YEAR, INI.INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
                ELSE (MD1.VALOR / DATEDIFF(MONTH, INI.INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF))) 
            END / 12 * FERPROP) / 3
    END AS TERCO_FERIAS_PROPORCIONAIS,
    CASE 
        WHEN DATEDIFF(MONTH, INI.INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
        ELSE ISNULL(MD1.VALOR / DATEDIFF(MONTH, INI.INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF)) / 12 * FERPROP, 0)
    END AS MEDIA_FERIAS_PROPORCIONAIS,
    FERPROP,
    ISNULL(COL.SALBASE / 30 * COL.DIAS_FERIAS_VENCIDAS, 0) AS FERIAS_VENCIDAS,
    MD3.VALOR AS MEDIA_FERIAS_VENCIDAS,
    (ISNULL(COL.SALBASE / 30 * COL.DIAS_FERIAS_VENCIDAS, 0) + ISNULL(MD3.VALOR, 0)) / 3 AS TERCO_FERIAS_VENCIDAS,
    COL.DIAS_FERIAS_VENCIDAS,
    COL.SALDO_ANTERIOR_FGTS,
    SFG.SALDO_SANKHYA_FGTS,
    COL.SALDO_ANTERIOR_FGTS + SFG.SALDO_SANKHYA_FGTS AS SALDO_FGTS,
    DEP.DESCRDEP,
    COL.DECTERSALARIO,
    ISNULL(MD2.VALOR_2, 0) AS MEDIA_DECTERCSALARIO,

    ROUND((ISNULL(COL.DECTERSALARIO, 0) + ISNULL(MD2.VALOR_2, 0)) * 0.08, 2) AS FGTS,
    FGS.FGTSMES,
    CASE 
        WHEN DATEDIFF(MONTH, INI.INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
        ELSE ISNULL(MD1.VALOR / DATEDIFF(MONTH, INI.INI_PERIODO_AQUISITIVO, ISNULL(COL.DTDEM, DR.DATA_REF)), 0)
    END AS MEDIA_PERIODO_AQUISITIVO,
    CASE
        WHEN DATEDIFF(MONTH, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 AND DATEDIFF(YEAR, COL.DTADM, ISNULL(COL.DTDEM, DR.DATA_REF)) = 0 THEN 0
        ELSE MD2.VALOR_3
    END AS MEDIA_12_MESES,
    ISNULL(INS.VALOR, 0) AS INSALUBRIDADE,
    ISNULL(PER.VALOR, 0) AS PERICULOSIDADE
FROM COLABORADORES COL 
INNER JOIN DATA_REFERENCIA DR ON DR.CODEMP = COL.CODEMP AND DR.CODFUNC = COL.CODFUNC
INNER JOIN TFPCAR CAR ON CAR.CODCARGO = COL.CODCARGO  
INNER JOIN TFPDEP DEP ON DEP.CODDEP = COL.CODDEP
LEFT JOIN SALDO_FGTS SFG ON SFG.CODEMP = COL.CODEMP AND SFG.CODFUNC = COL.CODFUNC
LEFT JOIN INIPERAQUI INI ON INI.CODEMP = COL.CODEMP AND INI.CODFUNC = COL.CODFUNC
LEFT JOIN ULTPERAQUI ULT ON ULT.CODEMP = COL.CODEMP AND ULT.CODFUNC = COL.CODFUNC
LEFT JOIN FGTS_MES FGS ON FGS.CODEMP = COL.CODEMP AND FGS.CODFUNC = COL.CODFUNC AND FGS.REFERENCIA = COL.REFERENCIA
LEFT JOIN COMP_SALDO CPS ON CPS.CODEMP = COL.CODEMP AND CPS.CODFUNC = COL.CODFUNC AND CPS.REFERENCIA = COL.REFERENCIA
LEFT JOIN MD1 ON MD1.CODEMP = COL.CODEMP AND MD1.CODFUNC = COL.CODFUNC
LEFT JOIN MD2 ON MD2.CODEMP = COL.CODEMP AND MD2.CODFUNC = COL.CODFUNC
LEFT JOIN MD3 ON MD3.CODEMP = COL.CODEMP AND MD3.CODFUNC = COL.CODFUNC
LEFT JOIN FERIAS_PROPORCIONAIS FPR ON FPR.CODEMP = COL.CODEMP AND FPR.CODFUNC = COL.CODFUNC
LEFT JOIN INSALUBRIDADE INS ON INS.CODEMP = COL.CODEMP AND INS.CODFUNC = COL.CODFUNC
LEFT JOIN PERICULOSIDADE PER ON PER.CODEMP = COL.CODEMP AND PER.CODFUNC = COL.CODFUNC
)

-- SELECT final com UNION ALL (mantendo sua lógica original)
select 
     b.CODEMP,
    NOMEEMP,
    b.CODFUNC,
    cc.CODCENCUS,
    cc.descrcencus as Centro_de_custo,
    NOMEFUNC,
    DTDEM,
    b.CODDEP,
    CODCARGO,
    DESCRCARGO,
    DTADM,
    INI_ULT_PER_AQUI,
    INI_PERIODO_AQUISITIVO,
    SALBASE,
    DIAS_SALDO_SALARIO,
    SALDO_SALARIO,
    CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado'  THEN 0 ELSE AVISO_PREVIO_INDENIZADO END AS AVISO_PREVIO_INDENIZADO,
    CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado' THEN 0 ELSE MEDIA_AVISO_PREVIO_INDENIZADO END AS MEDIA_AVISO_PREVIO_INDENIZADO,
    CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado' THEN 0 ELSE FGTS_AVISO_IND END AS FGTS_AVISO_IND,
    CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado' THEN 0 ELSE DECTER_API END AS DECTER_API,
    CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado' THEN 0 ELSE MEDIA_DECTER_API END AS MEDIA_DECTER_API,
     CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado' THEN 0 ELSE FGTS_DECTERC_API END AS FGTS_DECTERC_API,
     CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado' THEN 0 ELSE FERIAS_PROP_API END AS FERIAS_PROP_API,
     --CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado' THEN 0 ELSE TERCO_FERIAS_PROP_API END AS TERCO_FERIAS_PROP_API,
     CASE WHEN TIPO_AVISO_PREVIO ='Trabalhado' THEN 0 ELSE MEDIA_FERIAS_API END AS MEDIA_FERIAS_API,
    FERIAS_PROPORCIONAIS,
    (ISNULL(FERIAS_PROPORCIONAIS, 0) + ISNULL(MEDIA_FERIAS_PROPORCIONAIS, 0))/3 AS UM_TERCO_FERIAS_PROPROCIONAIS,
    MEDIA_FERIAS_PROPORCIONAIS,
    FERPROP,
    FERIAS_VENCIDAS,
    MEDIA_FERIAS_VENCIDAS,
    TERCO_FERIAS_VENCIDAS,
    DIAS_FERIAS_VENCIDAS,
    SALDO_ANTERIOR_FGTS,
    SALDO_SANKHYA_FGTS,
    SALDO_FGTS,
    b.DESCRDEP,
    DECTERSALARIO,
    MEDIA_DECTERCSALARIO,
    
    FGTS AS FGTS_DECTERCEIRO,
    
    MEDIA_PERIODO_AQUISITIVO,
    MEDIA_12_MESES,
    INSALUBRIDADE,                
    PERICULOSIDADE,
	-- CORREÇÃO DAS COLUNAS CALCULADAS

((ISNULL(SALBASE, 0)/30) * ISNULL(DIAS_SALDO_SALARIO, 0)) * 0.08 AS FGTS_MES,
(ISNULL(SALDO_FGTS,0) + ISNULL(SALDO_SALARIO* 0.08,0) + ISNULL(FGTS,0))*0.4 AS MULTA_FGTS,--(ISNULL(SALDO_FGTS, 0) + ((ISNULL(SALBASE, 0)/30) * ISNULL(DIAS_SALDO_SALARIO, 0)) * 0.08 + ISNULL(DECTERSALARIO, 0) * 0.08 + ISNULL(FGTS_DECTERC_API, 0) + ISNULL(FGTS_AVISO_IND, 0)) * 0.4 

-- TOTAL VERBAS RESCISÓRIAS AJUSTADO
(ISNULL(FERIAS_PROPORCIONAIS, 0) + ISNULL(MEDIA_FERIAS_PROPORCIONAIS, 0) + (ISNULL(FERIAS_PROPORCIONAIS, 0) + ISNULL(MEDIA_FERIAS_PROPORCIONAIS, 0))/3 + 
 ISNULL(MEDIA_FERIAS_VENCIDAS, 0) + ISNULL(TERCO_FERIAS_VENCIDAS, 0) + ISNULL(DECTERSALARIO, 0) + 
 ISNULL(MEDIA_DECTERCSALARIO, 0) + ISNULL(AVISO_PREVIO_INDENIZADO, 0) + ISNULL(DECTER_API, 0) + 
 ISNULL(MEDIA_DECTER_API, 0) + ISNULL(FERIAS_PROP_API, 0) + ISNULL(MEDIA_FERIAS_API, 0) + 
 ISNULL(TERCO_FERIAS_PROPORCIONAIS, 0) + (ISNULL(FERIAS_PROPORCIONAIS, 0) + ISNULL(MEDIA_FERIAS_PROPORCIONAIS, 0))) AS TOTAL_VERBAS_RESCISORIAS,

-- TOTAL FGTS MEDIDA
CASE WHEN p.TIPO_AVISO_PREVIO ='Trabalhado' THEN 
(ISNULL(SALDO_FGTS,0) + ISNULL(SALDO_SALARIO* 0.08,0) + ISNULL(FGTS,0))*0.4
+
isnull(FGTS,0)
+
((ISNULL(SALBASE, 0)/30) * ISNULL(DIAS_SALDO_SALARIO, 0)) * 0.08
 ELSE 
(ISNULL(SALDO_FGTS,0) + ISNULL(SALDO_SALARIO* 0.08,0) + ISNULL(FGTS,0))*0.4
+
isnull(FGTS,0)
+
((ISNULL(SALBASE, 0)/30) * ISNULL(DIAS_SALDO_SALARIO, 0)) * 0.08 + ISNULL(FGTS_AVISO_IND,0) + ISNULL(FGTS_DECTERC_API,0)
 
 END  TOTAL_FGTS,

-- TOTAL PASSIVO
(ISNULL(FERIAS_PROPORCIONAIS, 0) + ISNULL(MEDIA_FERIAS_PROPORCIONAIS, 0) + ISNULL(TERCO_FERIAS_PROPORCIONAIS, 0) + 
 ISNULL(MEDIA_FERIAS_VENCIDAS, 0) + ISNULL(TERCO_FERIAS_VENCIDAS, 0) + ISNULL(DECTERSALARIO, 0) + 
 ISNULL(MEDIA_DECTERCSALARIO, 0) + ISNULL(AVISO_PREVIO_INDENIZADO, 0) + ISNULL(DECTER_API, 0) + 
 ISNULL(MEDIA_DECTER_API, 0) + ISNULL(FERIAS_PROP_API, 0) + ISNULL(MEDIA_FERIAS_API, 0) + 
 ISNULL(TERCO_FERIAS_PROPORCIONAIS, 0) + (ISNULL(FERIAS_PROPORCIONAIS, 0) + ISNULL(MEDIA_FERIAS_PROPORCIONAIS, 0))) +
(((ISNULL(SALBASE, 0)/30) * ISNULL(DIAS_SALDO_SALARIO, 0)) * 0.08 + ISNULL(FGTS_AVISO_IND, 0) + ISNULL(FGTS_DECTERC_API, 0) + 
 (ISNULL(SALDO_FGTS, 0) + ((ISNULL(SALBASE, 0)/30) * ISNULL(DIAS_SALDO_SALARIO, 0)) * 0.08 + ISNULL(DECTERSALARIO, 0) * 0.08 + ISNULL(FGTS_DECTERC_API, 0) + ISNULL(FGTS_AVISO_IND, 0)) * 0.4 + 
 (ISNULL(DECTERSALARIO, 0) * 0.08)) AS TOTAL_PASSIVO
from base b 
left join TFPAVI avi on avi.CODFUNC = b.CODFUNC and avi.CODEMP = b.codemp
inner join TFPDEP d on d.CODDEP = b.coddep
inner join TSICUS cc on cc.codcencus = d.codcencus
CROSS JOIN PARAMETRO p  -- ADICIONE ESTA LINHA
where b.CODFUNC = 9256


